name: RedshiftMenuBar
options:
  xcodeVersion: "15.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
targets:
  RedshiftMenuBar:
    type: application
    platform: macOS
    sources:
      - path: Sources/RedshiftMenuBar
    info:
      path: Config/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bowlerr.RedshiftMenuBar
        PRODUCT_NAME: RedshiftMenuBar
        GENERATE_INFOPLIST_FILE: NO
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
    scheme:
      gatherCoverageData: false
      testTargets: []
